name: Test CPAW

on: 
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 12 * * *"
    
jobs:
  test-client:
    name: Test CPAW client
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start unittest
        run: python3.9 -m unittest tests.test_client
